version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
